# vim:set ft=dockerfile:
FROM debian:trixie AS builder

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -qq && \
    apt-get install -y gcc g++ make autoconf automake libtool \
       libfcgi-dev libxml2-dev libmemcached-dev \
       libboost-program-options-dev libcrypto++-dev libyajl-dev \
       libpqxx-dev zlib1g-dev libargon2-dev libfmt-dev \
       postgresql-16 postgresql-server-dev-all \
       --no-install-recommends && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy the main application.
COPY . ./

# Compile, install and remove source
RUN ./autogen.sh && \
    ./configure --enable-static --disable-shared --enable-yajl CXXFLAGS="-Wall -Wextra -Wpedantic -Wno-unused-parameter" && \
    make -j3 && \
    make check || ( cat ./test-suite.log ; exit 1 ) && \
    strip openstreetmap-cgimap

FROM debian:trixie

RUN apt-get update -qq && \
    apt-get install -y \
       libfcgi-bin libmemcached11 libboost-program-options1.74.0 \
       libxml2 libcrypto++8 libyajl2 libpqxx-7.8 zlib1g libargon2-1 argon2 libfmt9 \
       --no-install-recommends && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/openstreetmap-cgimap /usr/local/bin

RUN groupadd -g 61000 cgimap && \
    useradd -g 61000 -l -M -s /bin/false -u 61000 cgimap

USER cgimap

ENV CGIMAP_HOST db
ENV CGIMAP_DBNAME openstreetmap
ENV CGIMAP_USERNAME openstreetmap
ENV CGIMAP_PASSWORD openstreetmap
ENV CGIMAP_PIDFILE /dev/null
ENV CGIMAP_LOGFILE /dev/stdout
ENV CGIMAP_MEMCACHE memcached
ENV CGIMAP_RATELIMIT 204800
ENV CGIMAP_MAXDEBT 250
ENV CGIMAP_MODERATOR_RATELIMIT 1048576
ENV CGIMAP_MODERATOR_MAXDEBT 1024

EXPOSE 8000

CMD ["/usr/local/bin/openstreetmap-cgimap", "--port=8000", "--instances=30"]
