.TH OPENSTREETMAP-CGIMAP 1
.SH NAME
openstreetmap-cgimap \- FCGI version of the OpenStreetMap API
.SH SYNOPSIS
.B openstreetmap-cgimap
[
[\fB\-\-help]
[\fB\-\-daemon]
[\fB\-\-instances \fIINSTANCES\fR]
[\fB\-\-pidfile \fIPIDFILE\fR]
[\fB\-\-logfile \fILOGFILE\fR]
[\fB\-\-configfile \fICONFIGFILE\fR]
[\fB\-\-memcache \fISPEC\fR]
[\fB\-\-ratelimit \fILIMIT\fR]
[\fB\-\-moderator-ratelimit \fIMODERATOR_LIMIT\fR]
[\fB\-\-maxdebt \fIDEBT\fR]
[\fB\-\-moderator-maxdebt \fIMODERATOR_DEBT\fR]
[\fB\-\-port \fIPORT\fR]
[\fB\-\-socket \fISOCKET\fR]
] [
[\fB\-\-dbname \fIDBNAME\fR]
[\fB\-\-host \fIHOST\fR]
[\fB\-\-username \fIUSER\fR]
[\fB\-\-password \fIPASS\fR]
[\fB\-\-dbport \fIPORT\fR]
] [
[\fB\-\-update\-dbname \fIUPDATEDBNAME\fR]
[\fB\-\-update\-host \fIUPDATEHOST\fR]
[\fB\-\-update\-username \fIUPDATEUSER\fR]
[\fB\-\-update\-password \fIUPDATEPASS\fR]
[\fB\-\-update\-dbport \fIUPDATEPORT\fR]
] [
[\fB\-\-file \fIFILE\fR]
]
.SH DESCRIPTION
.B openstreetmap-cgimap
a C++ implementation of parts of the OpenStreetMap API as an FCGI process.
.SH OPTIONS
.TP
.BR \-\-help
Display help message and exit.
.TP
.BR \-\-daemon
Run as a daemon.
.TP
.BR \-\-instances =\fIINSTANCES\fR
Number of daemon instances to run.
Default is 5.
.TP
.BR \-\-pidfile =\fIPIDFILE\fR
Write pid to \fIPIDFILE\fR.
.TP
.BR \-\-logfile =\fILOGFILE\fR
File to write log messages to.
.TP
.BR \-\-configfile =\fICONFIGFILE\fR
File to read configuration values from.
.TP
.BR \-\-memcache =\fISPEC\fR
Memcache server specification.
.TP
.BR \-\-ratelimit =\fILIMIT\fR
Average number of bytes/s to allow each client.
.TP
.BR \-\-moderator-ratelimit =\fIMODERATOR_LIMIT\fR
Average number of bytes/s to allow each moderator.
.TP
.BR \-\-maxdebt =\fIDEBT\fR
Maximum debt (in Mb) to allow each client before rate limiting.
.TP
.BR \-\-moderator-maxdebt =\fIMODERATOR_DEBT\fR
Maximum debt (in Mb) to allow each moderator before rate limiting.
.TP
.BR \-\-port =\fIPORT\fR
FCGI port number (e.g. 8000) to listen on. This option is for backwards compatibility, please use \-\-socket for new configurations.
.TP
.BR \-\-socket =\fISOCKET\fR
FCGI port number (e.g. :8000) or UNIX socket to listen on.
.SS ApiDB backend options
.TP
.BR \-\-dbname =\fIDBNAME\fR
Database name.
.TP
.BR \-\-host =\fIHOST\fR
Database server host.
.TP
.BR \-\-username =\fIUSER\fR
Database user name.
.TP
.BR \-\-password =\fIPASS\fR
Database password.
.TP
.BR \-\-dbport =\fIPORT\fR
Database port number or UNIX socket file name.
.TP
.BR \-\-update\-dbname =\fIUPDATEDBNAME\fR
Database name to use for API write operations, if different from \-\-dbname.
.TP
.BR \-\-update\-host =\fIUPDATEHOST\fR
Database server host to use for API write operations, if different from \-\-host.
.TP
.BR \-\-update\-username =\fIUPDATEUSER\fR
Database user name to use for API write operations, if different from \-\-username.
.TP
.BR \-\-update\-password =\fIUPDATEPASS\fR
Database password to use for API write operations, if different from \-\-password.
.TP
.BR \-\-update\-dbport =\fIUPDATEPORT\fR
Database port number or UNIX socket file name to use for API write operations, if different from \-\-dbport.

